version: '3'

services:
  apache:
    container_name: apache
    build:
      context: .
      dockerfile: ./docker/apache/Dockerfile
    ports:
      - 80:80
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
    volumes:
      - ./src/dondake:/var/www/html
      - ./docker/apache/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
      - frontend
    networks:
      - net1
  frontend:
    build:
      context: .
      dockerfile: ./docker/front/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
  db:
    container_name: db
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    networks:
      - net1
    ports:
      - 3306:3306
networks:
  net1:
